from setuptools import setup

setup(
    name='watchout',
    version='0.1',
    packages=['env.lib.python3.6.distutils', 'env.lib.python3.6.encodings', 'env.lib.python3.6.importlib',
              'env.lib.python3.6.collections', 'env.lib.python3.6.site-packages.pip',
              'env.lib.python3.6.site-packages.pip._vendor', 'env.lib.python3.6.site-packages.pip._vendor.idna',
              'env.lib.python3.6.site-packages.pip._vendor.pep517',
              'env.lib.python3.6.site-packages.pip._vendor.pytoml',
              'env.lib.python3.6.site-packages.pip._vendor.certifi',
              'env.lib.python3.6.site-packages.pip._vendor.chardet',
              'env.lib.python3.6.site-packages.pip._vendor.chardet.cli',
              'env.lib.python3.6.site-packages.pip._vendor.distlib',
              'env.lib.python3.6.site-packages.pip._vendor.distlib._backport',
              'env.lib.python3.6.site-packages.pip._vendor.msgpack',
              'env.lib.python3.6.site-packages.pip._vendor.urllib3',
              'env.lib.python3.6.site-packages.pip._vendor.urllib3.util',
              'env.lib.python3.6.site-packages.pip._vendor.urllib3.contrib',
              'env.lib.python3.6.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'env.lib.python3.6.site-packages.pip._vendor.urllib3.packages',
              'env.lib.python3.6.site-packages.pip._vendor.urllib3.packages.backports',
              'env.lib.python3.6.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'env.lib.python3.6.site-packages.pip._vendor.colorama',
              'env.lib.python3.6.site-packages.pip._vendor.html5lib',
              'env.lib.python3.6.site-packages.pip._vendor.html5lib._trie',
              'env.lib.python3.6.site-packages.pip._vendor.html5lib.filters',
              'env.lib.python3.6.site-packages.pip._vendor.html5lib.treewalkers',
              'env.lib.python3.6.site-packages.pip._vendor.html5lib.treeadapters',
              'env.lib.python3.6.site-packages.pip._vendor.html5lib.treebuilders',
              'env.lib.python3.6.site-packages.pip._vendor.lockfile',
              'env.lib.python3.6.site-packages.pip._vendor.progress',
              'env.lib.python3.6.site-packages.pip._vendor.requests',
              'env.lib.python3.6.site-packages.pip._vendor.packaging',
              'env.lib.python3.6.site-packages.pip._vendor.cachecontrol',
              'env.lib.python3.6.site-packages.pip._vendor.cachecontrol.caches',
              'env.lib.python3.6.site-packages.pip._vendor.webencodings',
              'env.lib.python3.6.site-packages.pip._vendor.pkg_resources',
              'env.lib.python3.6.site-packages.pip._internal', 'env.lib.python3.6.site-packages.pip._internal.cli',
              'env.lib.python3.6.site-packages.pip._internal.req', 'env.lib.python3.6.site-packages.pip._internal.vcs',
              'env.lib.python3.6.site-packages.pip._internal.utils',
              'env.lib.python3.6.site-packages.pip._internal.models',
              'env.lib.python3.6.site-packages.pip._internal.commands',
              'env.lib.python3.6.site-packages.pip._internal.operations', 'env.lib.python3.6.site-packages.idna',
              'env.lib.python3.6.site-packages.click', 'env.lib.python3.6.site-packages.flask',
              'env.lib.python3.6.site-packages.flask.json', 'env.lib.python3.6.site-packages.wheel',
              'env.lib.python3.6.site-packages.wheel.cli', 'env.lib.python3.6.site-packages.jinja2',
              'env.lib.python3.6.site-packages.certifi', 'env.lib.python3.6.site-packages.chardet',
              'env.lib.python3.6.site-packages.chardet.cli', 'env.lib.python3.6.site-packages.urllib3',
              'env.lib.python3.6.site-packages.urllib3.util', 'env.lib.python3.6.site-packages.urllib3.contrib',
              'env.lib.python3.6.site-packages.urllib3.contrib._securetransport',
              'env.lib.python3.6.site-packages.urllib3.packages',
              'env.lib.python3.6.site-packages.urllib3.packages.backports',
              'env.lib.python3.6.site-packages.urllib3.packages.ssl_match_hostname',
              'env.lib.python3.6.site-packages.requests', 'env.lib.python3.6.site-packages.werkzeug',
              'env.lib.python3.6.site-packages.werkzeug.debug', 'env.lib.python3.6.site-packages.werkzeug.contrib',
              'env.lib.python3.6.site-packages.markupsafe', 'env.lib.python3.6.site-packages.setuptools',
              'env.lib.python3.6.site-packages.setuptools.extern', 'env.lib.python3.6.site-packages.setuptools._vendor',
              'env.lib.python3.6.site-packages.setuptools._vendor.packaging',
              'env.lib.python3.6.site-packages.setuptools.command', 'env.lib.python3.6.site-packages.itsdangerous',
              'env.lib.python3.6.site-packages.pkg_resources', 'env.lib.python3.6.site-packages.pkg_resources.extern',
              'env.lib.python3.6.site-packages.pkg_resources._vendor',
              'env.lib.python3.6.site-packages.pkg_resources._vendor.packaging'],
    url='',
    license='',
    author='ericd',
    author_email='eric.diaz13@yahoo.com',
    description='Runs the API endpoint that a phone is supposed to use.'
)
